### PR TITLE
Fixed broken grabbers

### PR DESCRIPTION
**Pull request by indecDavid**

### CODE REVIEW

**Comment by JavidShoaei** [comment]
Thank you for your contribution.
I disabled the Instagram grabber because a while ago Instagram started to require authentication before displaying the page.
Your InstagramGrabber doesn't work either even for public posts. I'll add authentication to grabbers that need it when I find time.
Your PornHub grabber works though which is fine for merging but for some reason you have removed the `PackageLicenseExpression` from the project. Please fix it and I'll merge.

**Comment by indecDavid** [comment]
FYI, I deleted the PackageLicenseExpression due to the compilation error that resulted by it existing (https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5035).  


`
The PackageLicenseUrl cannot be used in conjunction with the PackageLicenseFile and PackageLicenseExpression.`

**Comment by indecDavid** [comment]
Did the instagram grabber tests fail for you (both the one you wrote and the one I added)?  Both tests passed for me and the desktop app downloaded the video correctly for both of them when I tested it.

**Comment by JavidShoaei** [comment]
When did you test it? Instagram requires authentication I don't understand how it worked for you. Of course it used to work about a year ago, but not anymore.

**Comment by indecDavid** [comment]
I tested it a moment before creating this pull request.  Just now I did a completely new clone of this fork to my PC (to make sure I didn't mess something up with that repo any my clone was out of sync or something).  From that fresh checkout, I built using VS 2019 and then ran the desktop application (debug) from visual studio 2019 (latest preview version).

I then pasted in this url and it grabbed the video title and thumbnail: https://www.instagram.com/p/CIE3H_-DDJ1/?hl=en

I then clicked Download and it downloaded the video.

I also did the same thing with the url you had in your test (https://www.instagram.com/p/CAs5qr7gYQJ/?utm_source=ig_web_copy_link) and it all worked correctly.

**Comment by JavidShoaei** [comment]
I tested this right now. I've not logged into Instagram with my browser. Using the browser, I navigate to https://www.instagram.com/p/CIE3H_-DDJ1/?hl=en and it redirects to https://www.instagram.com/accounts/login/?next=/p/CIE3H_-DDJ1/%3Fhl%3Den
Please do the same now. Doesn't the same thing happen to you?

**Comment by indecDavid** [comment]
I did try going to https://www.instagram.com/p/CIE3H_-DDJ1/?hl=en in a new "private window" in firefox and it brought up the post (did not require me to log in).  Did you try doing this in a private or incognito window?

**Comment by indecDavid** [comment]
Here is a screenshot of what I see when I go to that url (notice that there are options for me to log in so you can see that I am not logged in when I brought this up).
firefox_i1ZFWbNGgD

**Comment by JavidShoaei** [comment]
Wow it's either A/B testing or its limited by country. I don't really know, but I'll accept your merge request to unofficially support Instagram. However, I will add authentication support when I find the time.

**Comment by indecDavid** [comment]
Thanks Javid, perhaps it is difference based on country (I am in the US) or maybe they have different logic based on your IP (for example some websites require more verification before use if you have a VPN IP address).

**Pull request merged**
